# Generated by Django 4.1.7 on 2023-03-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('discipline_name', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('solution', models.JSONField()),
            ],
        ),
    ]
